name: build

on:
  push:
    branches: [ ci ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm install

      - run: npm run build

      - name: Create archive for manual installation
        run: npm pack

      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: '*.tgz'
          retention-days: 7